export enum ActiveTutorActionTypes {
    FETCH_TUTOR_INFO_REQUEST = '@@activeTutor/FETCH_TUTOR_INFO_REQUEST',
    FETCH_TUTOR_INFO_REQUEST_SUCCESS = '@@activeTutor/FETCH_TUTOR_INFO_REQUEST_SUCCESS',
    FETCH_TUTOR_INFO_REQUEST_FAILURE = '@@activeTutor/FETCH_TUTOR_INFO_REQUEST_FAILURE',
    SET_STUDENT_REQUEST = '@@activeTutor/SET_STUDENT_REQUEST',
}