export enum AuthActionTypes {
    AUTHENTICATE_USER = '@@auth/AUTHENTICATE_USER',
    SET_REFRESH_PROMISE = '@@auth/SET_REFRESH_PROMISE',
    REMOVE_REFRESH_PROMISE = '@@auth/REMOVE_REFRESH_PROMISE',
};