export enum ReviewsByTutorActionTypes {
    FETCH_REVIEWS_REQUEST = '@@reviews/FETCH_REVIEWS_REQUEST',
    FETCH_REVIEWS_SUCCESS = '@@reviews/FETCH_REVIEWS_SUCCESS',
    FETCH_REVIEWS_FAILURE = '@@reviews/FETCH_REVIEWS_FAILURE',
}