export enum TutorsActionTypes {
    FETCH_TUTORS_REQUEST = '@@tutors/FETCH_TURORS_REQUEST',
    FETCH_TUTORS_SUCCESS = '@@tutors/FETCH_TUTORS_SUCCESS',
    FETCH_TUTORS_FAILURE = '@@tutors/FETCH_TUTORS_FAILURE',
    FETCH_TUTOR_REQUEST = '@@tutors/FETCH_TUTOR_REQUEST',
    FETCH_TUTOR_SUCCESS = '@@tutors/FETCH_TUTOR_SUCCESS',
    FETCH_TUTOR_FAILURE = '@@tutors/FETCH_TUTOR_FAILURE',
    SELECT_TUTOR = '@@tutors/SELECT_TUTOR',
}